// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shop_back.DataAccess;

#nullable disable

namespace Shop_back.DataAccess.Migrations
{
    [DbContext(typeof(ShopBackDbContext))]
    [Migration("20260409173927_changecolumnDiiscount")]
    partial class changecolumnDiiscount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shop_back.DataAccess.Entities.Items.SmartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Smarts");
                });

            modelBuilder.Entity("Shop_back.DataAccess.Entities.Items.SmartVariantsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<Guid>("SmartId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SmartId");

                    b.ToTable("SmartVariants");
                });

            modelBuilder.Entity("Shop_back.DataAccess.Entities.Items.SmartVariantsEntity", b =>
                {
                    b.HasOne("Shop_back.DataAccess.Entities.Items.SmartEntity", "Smart")
                        .WithMany("Variants")
                        .HasForeignKey("SmartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Shop_back.Core.Models.Items.Smart.Discount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("SmartVariantsEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("Percent")
                                .HasColumnType("integer");

                            b1.HasKey("SmartVariantsEntityId");

                            b1.ToTable("SmartVariants");

                            b1.WithOwner()
                                .HasForeignKey("SmartVariantsEntityId");
                        });

                    b.Navigation("Discount");

                    b.Navigation("Smart");
                });

            modelBuilder.Entity("Shop_back.DataAccess.Entities.Items.SmartEntity", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
